import Nav from  '../components/nav/Nav';
import { UserProvider } from '../context/userContext';
import './globals.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body>
          {/* <Nav />
          <main className="body-spacing "> */}
            <UserProvider>
              <Nav />
              <main className="body-spacing ">
                {children}
              </main>
            </UserProvider>
          {/* </main> */}
        </body>
      </html>
    )
}